version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.10.0
    steps:
      - checkout
      - run:
          name: Run Hello World
          command: node helloWorld.js
      - run:
          name: Check Path
          command: pwd

workflows:
  workflow-name:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - main
                - cron
    jobs:
      - build
