version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Run Hello World
          command: node helloWorld.js
      - run:
          name: Check Path
          command: pwd