version: 2
jobs:
  build:
    docker:
      - image: circleci/node:18.15.0
        auth:
          username: ramchampogi
          password: $dockerhubpassword # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Run Hello World
          command: node helloWorld.js
      - run:
          name: Check Path
          command: pwd