version: 2
jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run:
          name: Run Hello World
          command: node helloWorld.js
      - run:
          name: Check Path
          command: ls