version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:18.15.0
        auth:
          username: ramchampogi
          password: $dockerhubpassword 
    steps:
      - checkout
      - run:
          name: Run Hello World
          command: node helloWorld.js
      - run:
          name: Check Path
          command: pwd
workflows:
  build:
    jobs:
      - build:
          context: dockerhub