version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: selenium/hub:3.141.59-iron
    working_directory: ~/repo # https://circleci.com/docs/configuration-reference/?query=CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - run:
          name: Run Hello World
          command: node helloWorld.js
      - run:
          name: Check Path
          command: pwd
  test:
    docker:
      - image: circleci/node:10
      - image: selenium/hub:3.141.59-iron
    working_directory: ~/repo # https://circleci.com/docs/configuration-reference/?query=CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - run:
          name: Run Hello World
          command: node helloWorld.js
      - run:
          name: Check Path
          command: pwd

workflows:
  version: 2
  workflow-name:
    jobs:
      - build
      - test:
          requires:
            - build

  cron:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - cron
    jobs:
      - build

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
